export const enum Paths {
  Example = 'example',
  Startup = 'startup',
  Home = 'home',
  Palette = 'palette',
  Settings = 'settings',
  Search = 'search',
  PaintingDetail = 'paintingDetail',
  Collection = 'collection',
  ArtistProfile = 'artistProfile',
  Visits = 'visits',
  VisitDetail = 'visitDetail',
  MuseumBrowser = 'museumBrowser',
  MuseumCollection = 'museumCollection',
  VisitPalette = 'visitPalette',
  ViewPalette = 'viewPalette',
  CanonPalette = 'canonPalette',
  ViewCanon = 'viewCanon',
  Auth = 'auth'
}